### ISSUE TITLE
Mods request

### ISSUE THREAD

**Issue by purpl3-yt** [Venage5603/Simple-Optimizations#1]
### Hi, I'd like to offer a couple of mods
* Cull Less Leaves - Adds culling to leaf blocks, providing a huge performance boost over vanilla ([link](https://www.curseforge.com/minecraft/mc-mods/cull-less-leaves))
* FerriteCore - Memory usage optimizations ([link](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric))
* Exordium - Renders the GUI at a lower fixed framerate ([link](https://www.curseforge.com/minecraft/mc-mods/exordium))
* ImmediatelyFast - Improves the immediate mode rendering performance of the client ([link](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast))
* Krypton - Optimize the Minecraft networking stack ([link](https://www.curseforge.com/minecraft/mc-mods/krypton))

All mods support 1.20.1 version!

**Comment by Venage5603** [comment]
krypton, immediatelyfast and ferritecore are already in the modpack. cull less leaves does not support more culling because moreculling already culls leaves.  but i will take exordium into consideration :)
